blog/urls.py
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from config.urls import path

app_name = BlogConfig.name

urlpatterns = [
    path('create/',  never_cache(BlogCreateView.as_view()), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/',  never_cache(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    header = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, **NULLABLE, verbose_name='slug')
    content = models.TextField(**NULLABLE, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    create_date = models.DateField(max_length=50, **NULLABLE, verbose_name='Дата создания')
    is_public = models.BooleanField(default=True, verbose_name='Признак публикаций')
    count_views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f"{self.header} {self.slug} {self.content} {self.count_views}"

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('header', 'content',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid:
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.header)
            new_blog.save()
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_public=True)

        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()

        return self.object

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('header', 'content',)

    def form_valid(self, form):
        if form.is_valid:
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.header)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Блог</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Главная</a>
    </nav>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Блог</h1>
</div>


<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Блог
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted">+79834223423</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:list' %}">Главная</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="col-12"></div>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите ли удалить статью {{ object.header }} ?</p>
                    <button type="submit" class="btn btn-danger">
                        Подтвердить
                    </button>
                    <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="col-12">
    <div class="row">


        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Статья '{{ object.header }}' ({{ object.slug }})
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.content }}
                    </p>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.count_views }}
                </div>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="col-12"></div>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <a></a>
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                        Создать
                        {% endif %}

                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="row text-center">
        <div class="col-12">
            <div class="col-12">
                <a class='btn btn-primary' href="{% url 'blog:create' %}">Добавить материал</a>
            </div>
        </div>
        {% for object in object_list %}
            <div class="p-3 col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.header }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.content|truncatechars:30}}</li>
                        </ul>
                        <div class="btn-group">
                            <a class="p-2 btn btn-outline-success" href="{% url 'blog:view' object.pk%}">view</a>
                            <a class="p-2 btn btn-outline-primary" href="{% url 'blog:edit' object.pk %}">edit</a>
                            <a class="p-2 btn btn-outline-danger" href="{% url 'blog:delete' object.pk %}">delete</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}