blog/urls.py
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView
from config.urls import path

app_name = BlogConfig.name

urlpatterns = [
    path('create/',  never_cache(BlogCreateView.as_view()), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/',  never_cache(BlogUpdateView.as_view()), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete')
]

catalog/urls.py
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, index, contacts, CategoryListView, ProductCreateView, ProductUpdateView, \
    ProductDetailView, ProductDeleteView
from config.urls import path

app_name = CatalogConfig.name

urlpatterns = [
    path('', index, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('pruduct/<int:pk>', ProductListView.as_view(), name='product_list'),
    path('product/view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_view'),
    path('product/create/',  never_cache(ProductCreateView.as_view()), name='product_create'),
    path('<int:pk>/product/edit/',  never_cache(ProductUpdateView.as_view()), name='product_edit'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, verify_email

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
    path('verify/<str:token>/', verify_email, name='verify_email'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name_category = models.CharField(max_length=100, verbose_name='Наименование')
    description_category = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f"{self.name_category} {self.description_category}"

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категорий'


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    preview = models.ImageField(upload_to='catalog/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    create_date = models.DateField(max_length=50, **NULLABLE, verbose_name='Дата создания')
    date_change = models.DateField(max_length=50, **NULLABLE, verbose_name='Дата последнего изменения')
    users = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Пользователь'
    )

    def __str__(self):
        return f"{self.name} {self.description} {self.preview} {self.price}"

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Version(models.Model):
    SIGN_TRUE = True
    SIGN_FALSE = False
    SIGN = ((SIGN_TRUE, 'Активен',),
            (SIGN_FALSE, 'Неактивен'),)

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.IntegerField(verbose_name='Номер версий')
    version_name = models.CharField(max_length=100, verbose_name='Название версий')
    version_sign = models.BooleanField(default=SIGN_TRUE, choices=SIGN, verbose_name='Признак версий')

    def __str__(self):
        return f'{self.version_name}/{self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версий'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('users',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        if cleaned_data.lower() in forbidden_words:
            raise forms.ValidationError('Нельзя использовать запрещённые слова!')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['name']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        if cleaned_data.lower() in forbidden_words:
            raise forms.ValidationError('Нельзя использовать запрещённые слова!')

        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from catalog.apps import CatalogConfig
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Category, Version
from catalog.services import get_categories_cache

app_name = CatalogConfig


@login_required
def index(request):
    return render(request, 'catalog/home.html')


@login_required
def contacts(request):
    return render(request, 'catalog/contacts.html')


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'catalog/category.html'
    extra_context = {
        'title': 'Категорий'
    }

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['object_list'] = get_categories_cache()
        return context_data


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    success_url = reverse_lazy('catalog:category')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category=self.kwargs.get('pk'))

        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category.pk'] = category_item.pk

        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:category')

    def form_valid(self, form):
        self.object = form.save()
        self.object.users = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:category')

    def get_success_url(self):

        return reverse('catalog:product_edit', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:category')
    permission_required = 'catalog.delete_product'

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Каталог</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:category' %}">Категорий</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
    <p class="lead">Категорий товаров на любой выбор!</p>
</div>

<div class="container">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Каталог
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted">+79834223423</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name_category|title }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.description_category|slice:100 }}</li>
                        </ul>
                        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list' object.pk%}">Перейти</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="container">
        <div class="row text-start">
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr class="table-info">
                                <td class="w-25">Страна</td>
                                <td>Россия</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>12-5124341</td>
                            </tr>
                            <tr class="table-info">
                                <td class="w-25">Адрес</td>
                                <td>г. Москва, ул. Дорожная 12</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                       required>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Сообщите о проблеме" required></textarea>
                            </div>
                            <button type="submit" class="btn  btn-lg btn-info btn-outline-light">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12"></div>
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите ли удалить продукт {{ object.name }} ?</p>
                        <button type="submit" class="btn btn-danger">
                            Подтвердить
                        </button>
                        <a href="{% url 'catalog:category' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
    <div class="row">


        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object.name }}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        Описание: {{ object.description }}
                    </p>
                </div>
                <div class="card-footer h5">
                    Цена: {{ object.price }} рублей
                </div>
                <div class="card-footer">
                    {{ object.users|default:'Нету пользователя' }}
                </div>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row">
        {% if not object %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Создание продукта
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                                Создать
                        </button>
                    </div>
                </div>
            </div>
            </form>
        {% endif %}

    <form method="post" class="row">
        {% if object %}
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Редактирование продукта
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                                Сохранить
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Версий продукта
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}

                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    </form>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

    <div class="row text-center">
        <div class="col-12">
            <div class="col-12">
                <a class='btn btn-primary' href="{% url 'catalog:product_create' %}">Добавить продукт</a>
            </div>
        </div>

        {% for object in object_list %}
            <div class="col-3 mt-5">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name|title }}</h4>
                    </div>
                    <div class="card-body">
                        <img class="card-img-top"
                             src="{{ object.preview|my_media }}"
                             alt="Card image cap">
                        <h3 class="card-title pricing-card-title">{{ object.price }} руб</h3>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.description|slice:100 }}</li>
                        </ul>
                        <div class="btn-group h5 mb-auto">
                            <a class="p-2 btn btn-outline-success "
                               href="{% url 'catalog:product_view' object.pk %}">Обзор</a>
                            <a class="p-2 btn btn-outline-primary " href="{% url 'catalog:product_edit' object.pk %}">Редактирование</a>
                            {% if perms.catalog_delete_product %}
                                <a class="p-2 btn btn-outline-danger "
                                   href="{% url 'catalog:product_delete' object.pk %}">Удаление</a>
                            {% endif %}
                        </div>
                        <div class="mt-1">
                            <button type="submit" href="#" class="btn btn-outline-secondary">Купить</button>
                        </div>
                        {% for version in object.version_set.all %}
                            {% if version.version_sign %}
                                <div class="card-footer mt-1">
                                    Номер активной версий: {{ version.version_number }}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}